### ISSUE TITLE
How to access .DocumentDirectory on iOS

### ISSUE THREAD

**Issue by vinbhai4u** [nvzqz/FileKit#13]
When I try the below 

Path.UserDocuments

Path has no members UserDocuments

it has only 3 UserCache, UserHome, UserTemporary

**Comment by phimage** [comment]
`.UserDocuments` is only OSX currently

We have a [task](https://trello.com/c/W2pyr3Ym/11-paths) to add other valid path to iOS

**Comment by vinbhai4u** [comment]
thanks @phimage for now is there any work arounds??

I am trying to download files using Alamofire, needs to save somewhere and read it, what do u suggests?

**Comment by phimage** [comment]
You can download in `. UserTemporary`

**Comment by nvzqz** [comment]
Some directories on iOS were excluded that may exist. So that's an error on my part. I haven't gotten around to seeing which ones actually do exist, such as Documents.
