### ISSUE TITLE
How to rename?

### ISSUE THREAD

**Issue by innoreq** [nvzqz/FileKit#16]
Although FileKit is a really great library, I have a small problem with it.
Situation: I want to copy a file from one location to another location with a different name. With the `copyToPath` method I get the file with the original name from path1 to path2. But: How do I rename the file there? Changing the name does not succeed, as name is read-only. So, I'm stuck a bit...
Perhaps you might give me hint for that - thanks a lot in advance!

- Hardy

**Comment by phimage** [comment]
`moveFileToPath` maybe
