### ISSUE TITLE
iOS should have UserDocuments as well

### ISSUE THREAD

**Issue by tuyencoder** [nvzqz/FileKit#17]
Can you allow Path.UsersDocuments for iOS in addition to OSX?
And can you make Path.pathInUserDomain, Path.pathsInDomains public? This way I can extend Path with more iOS paths such as UsersDocuments

**Comment by phimage** [comment]
maybe there is no new release from my commit b29f0015395e427ef7771687e47aaf2aa7b95825

try to use code from head

**Comment by sun-fox-cj** [comment]
yes, UsersDocuments should for iOS, or make pathInUserDomain for public not private

**Comment by nvzqz** [comment]
The `develop` branch already has UserDocuments. It'll be available in the next release.
