### ISSUE TITLE
NSFileHandle-based implementation and exceptions

### ISSUE THREAD

**Issue by objecthub** [nvzqz/FileKit#22]
I noticed that FileKit is based on NSFileHandle.  NSFileHandle has an API that is based on (Objective-C) exceptions. The FileKit codebase currently does not catch those. IMO, this is required to make it possible to safely use FileKit (without arbitrary application terminations).

**Comment by phimage** [comment]
thank you for your remark, but please could you be more specific. Are you talking about TextFile? And stream reading

**Comment by phimage** [comment]
I close due to lack of information
