### ISSUE TITLE
Support for hard links

### ISSUE THREAD

**Issue by tfe** [nvzqz/FileKit#23]
Hi, I just ran into a case where I had to user a hard link instead of a symlink and had to fall back to NSFileManager to accomplish it. The API is almost identical to the symlink function:

```
createSymbolicLinkAtURL(_:withDestinationURL:)
createSymbolicLinkAtPath(_:withDestinationPath:)
linkItemAtURL(_:toURL:)
linkItemAtPath(_:toPath:)
```

Docs: https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/index.html#//apple_ref/doc/uid/20000305-SW30

Thanks! If I have some time I'll add this and submit a PR, but I wanted to at least raise the flag so the issue is logged.

**Comment by nvzqz** [comment]
Done eaf3a98604028b5afe51224e6b60ebaf33f4197e
