### ISSUE TITLE
Support Linux?

### ISSUE THREAD

**Issue by rbukovansky** [nvzqz/FileKit#28]
Hi, will FileKit support Linux as well? Currently I'm not able to build 3.0.0 tag due issue with Image+File.swift where is WatchKit imported, which is something that doesn't exist on Linux version of Swift.
Thanks.

**Comment by nvzqz** [comment]
Thanks for pointing this out! Fixed in 4d928bc99cc075b9d6c0c4293ba472be4b7eed02.

**Comment by rbukovansky** [comment]
Looks promising, but could you please tag that commit so I can use it with Swift Package Manager? Thanks.

**Comment by rbukovansky** [comment]
Could we please get that tag 4.0.0, best would be 4.0.0-beta1?
Swift Package Manager (Swift 3.0) can handle that with this info in Package.swift:

```
dependencies: [
        .Package(url: "https://github.com/nvzqz/FileKit", Version(4, 0, 0, prereleaseIdentifiers: ["beta1"]))
]
```

Thanks a lot.
