### ISSUE TITLE
How to use the `Path` class while already having a class named `Path`?

### ISSUE THREAD

**Issue by ahmedk92** [nvzqz/FileKit#29]
I tried `FileKit.Path` with no gain.

**Comment by phimage** [comment]
maybe try to import the `struct`
```swift
import struct FileKit.Path
```

https://andybargh.com/lifetime-scope-and-namespaces-in-swift/

**Comment by nvzqz** [comment]
Fixed with 9e075da

**Comment by protosse** [comment]
```Swift
import struct FileKit.Path
typealias FPath = FileKit.Path

import SwiftUI
```
hello, I use SwiftUI and FileKit together, and SwiftUI also has a struct named `Path`.
The following code will report error 
`Binary operator '+(_:_:)' cannot be applied to operands of type 'Path' and 'String'`
```Swift
let outputPath = FPath.userDesktop + "output.mov"
```

**Comment by phimage** [comment]
that's weird! ( swiftui `Path` ❤️  https://github.com/phimage/morphi )

did you try to do
```swift
import struct FileKit.Path
typealias FPath = FileKit.Path
```
in other file of your project, a file without SwiftUI? just to declare the alias and use it here

or add  (based on https://stackoverflow.com/questions/39537103/is-it-possible-to-alias-an-import )
```swift
typealias Path = SwiftUI.Path
```

I do not think that aliased import exists ... (`import struct FileKit.Path as FPath`)

**Comment by protosse** [comment]
@phimage thanks to replay, finally I add
```Swift
import FileKit
import SwiftUI

//typealias FPath = FileKit.Path
typealias SPath = SwiftUI.Path

let outputPath = Path.userDesktop + "output.mov"
```
this works well.
but why 
![image](https://user-images.githubusercontent.com/30048222/67447940-13191580-f648-11e9-8f0a-a9358d9a85b1.png)
