### ISSUE TITLE
Is this possible to move folder, with all files in it, recursively?

### ISSUE THREAD

**Issue by fantomnotabene** [nvzqz/FileKit#36]
I got an error when try to move it using function `moveTo()` on `Path`.

**Comment by phimage** [comment]
please provide the error when creating an issue
maybe the destination already exist? if yes you must delete all files at destination
or If you want something more evolved 
 
 a method to copy recursively file by file using visitor pattern and/or provide a delegate  which decide for each files what to do if the destination already exist.
 then in delegate developper can
- provide and UI to ask user what to do 
- or choose the more recent file
- or override all files
- or pass all files
- or stop copy
- ...

Maybe maybe maybe If I need for my own purpose, I will implement it , but not now
