### ISSUE TITLE
Support Swift 4

### ISSUE THREAD

**Issue by Vitaliyy-jomedia** [nvzqz/FileKit#48]
When do you plan to add support for Swift 4

**Comment by Ponyboy47** [comment]
Just opened a pull request for Swift4 support: #49 

It really wasn't too bad to get everything compiling on swift4

**Comment by nvzqz** [comment]
With the official release of Swift 4, this is now top priority. Seeing as #49 has a few unwanted changes, I'll attempt to update the project myself this upcoming weekend.

I'm very sorry for the long delay.

**Comment by liufsd** [comment]
1

**Comment by phimage** [comment]
need help @nvzqz ?
I can do it this week end

**Comment by nvzqz** [comment]
@phimage Yes please, if you wouldn't mind. School work is keeping me busy and this feels more like a chore than anything else 😅.

**Comment by phimage** [comment]
73b86c74d3d8a91de0fd68095cc8cfd5f2a3d24e

- Conversion to swift 4
- travis file for Continuous integration. You can enable it by logging into https://travis-ci.org
- Keep the original error cause in FileKitError
  - In a lot of case we want to know why the operation failed
  - Introduce a derived ReasonError in FileKitError in some specific case where this is no Foundation Error
- fix swiftlint warning

**Comment by nvzqz** [comment]
@phimage thank you very much for your work on this. I'll tag and release your changes soon.

**Comment by nvzqz** [comment]
Released v5.0.0 on CocoaPods

**Comment by theeternalsw0rd** [comment]
Using v5.0.0 xcode has deprecation warning about ExpressibleByStringInterpolation in Path.swift with swift 4. Seems to indicate removal is imminent. Perhaps a dot release of swift 4 will break it.

**Comment by phimage** [comment]
@theeternalsw0rd this is an other topic.
This warning has been already there in swift3
I did not find any replacement for this feature. I someone find it, please PR.
