### ISSUE TITLE
Support Decodable/Encodable (Swift 4)

### ISSUE THREAD

**Issue by phimage** [nvzqz/FileKit#50]
In the past, I try to make some utility functions to work with NSCoding (branch feature-nscoding), write and read JSON

In swift 4 Decodable/Encodable (and [Codable](https://developer.apple.com/documentation/swift/codable)) allow to have a better interface to serialize objects

We can
- [x] write to file an `Encodable` object
- [x] write to file an array of `Encodable` objects
- [x] read from file an `Decodable` object
- [x] read from file an array of `Decodable` objects

That could be done only after merging #49

**Comment by nvzqz** [comment]
These would be good changes to have but behind `#if swift(>=3.2)`.

**Comment by phimage** [comment]
I make a class FileKit to get shared JSON/PropertyList encoder/decoder
And also for easy to use functions
```swift
try FileKit.write(encodable, to: .userTemporary + "test")
let decodable: MyClass = try FileKit.read(from:  .userTemporary + "test")
```
Array of Codable are codable, so the same functions work

--- 

I add protocols `JSONReadable`, `JSONWritable` (or `PropertyListReadable`/`PropertyListWritable`) to be able to implement `Readable` and `Writable` and create `File` with specific type just by implementing protocols (an alias name could be added like `JSONReadableWritable` if necessary)
```swift
struct TestJSONCodable: Codable {
    let string: String
    let integer: Int
}
extension TestJSONCodable: JSONWritable, JSONReadable {}
```
```swift
let encodable = TestJSONCodable(string: "test", integer: 9)
let codableFile = File<TestJSONCodable>(path:  .userTemporary + "testcodable.json")
try codableFile.write(encodable)
let decodable: TestJSONCodable = try codableFile.read()
```

**Comment by phimage** [comment]
committed but need some doc in README
