### ISSUE TITLE
 Cannot convert value of type '[FileAttributeKey : Any]' to expected argument type '[String : Any]?'

### ISSUE THREAD

**Issue by matthewxu** [nvzqz/FileKit#51]
Xcode9 
after pod install 
Swift Compiler Error Group:
/Users/matthewxu/project/LiLiTools/Pods/FileKit/Sources/FileProtection.swift:126:82: Cannot convert value of type '[FileAttributeKey : Any]' to expected argument type '[String : Any]?'
on `manager.createFile(atPath: _safeRawValue, contents: nil, attributes: attributes) { `
in the following codes
 ```
public func createFile(_ fileProtection: FileProtection) throws {
        let manager = FileManager()
        let attributes: [FileAttributeKey : Any] = [.protectionKey: fileProtection] // todo test

        if !manager.createFile(atPath: _safeRawValue, contents: nil, attributes: attributes) { 
            throw FileKitError.createFileFail(path: self)
        }
    }
```

Any one meet this issue and how to solve it

**Comment by matthewxu** [comment]
I solved this issue need to import the framework by manual instead of pod.
Any one import the framework successful by pod?

**Comment by MainasuK** [comment]
I got the same issue when I use FileKit 4.0.1. It's looks like the pods update for Swift 4.0 somehow.
You can try FileKit 5.0.0 with Swift 4.

OR

Use that pod with Swift 3.2.
`pod 'FileKit', :git => 'https://github.com/nvzqz/FileKit.git', :commit  => '8599917'`

**Comment by phimage** [comment]
I made a Swift 3.2 branch for swift3 for xcode 9
Put a .swift-version file with 3.2 inside your project; it could help cocoapod to choose the correct version

**Comment by sonnytron** [comment]
This has to be a bug because when I pull down the project and attempt to compile it with [String: Any], I get thrown an error because file manager expects FileAttributeKey: Any.  
This is regardless of building Swift 4 or Swift 3.2.  
My project is Swift 4, but I pulled down my Cocoapods as Swift 3.2 so I can upgrade them piecewise.  
So when you have Swift 3.2 Pods on a Swift 4 project, FileManager changes the attributes for the create file method to [String: Any].

**Comment by phimage** [comment]
@sonnytron iOS or macOS ? 

How did you specify that FileKit use swift 3.2 ? did you check it 
![xcode swift version](https://i.stack.imgur.com/JRrgk.png)
https://stackoverflow.com/questions/45198857/how-to-build-a-xcode-9-project-with-swift-4-0-using-pods-in-swift-3


- swift3.2 branch compile on iOS and macOS with Xcode 9.2 using swift 3.2
- develop & master branch compile on iOS and macOS with Xcode 9.2 using swift 4.0

- v5.0.0 is on latest commit of master branch, so for swift4 -> use v5.0.0
- for swift3.2 specify the branch or the commit in your Podfile
