### ISSUE TITLE
CocoaPods version not updated

### ISSUE THREAD

**Issue by dingwilson** [nvzqz/FileKit#57]
Your podspec/releases show `5.1.0`, but cocoapods only has up to `5.0.0`. Please run `pod trunk push` to update cocoapods with your latest podspec. Thanks!

**Comment by mobilinked** [comment]
Same issue here, would you please help to update the version?

**Comment by phimage** [comment]
```
pod trunk push --allow-warnings
```
I have not the right to do it

@nvzqz could you do it or add me to cocoapod?

**Comment by phimage** [comment]
🎉  Congrats

 🚀  FileKit (5.1.0) successfully published
 📅  September 17th, 22:38
 🌎  https://cocoapods.org/pods/FileKit
 👍  Tell your friends!
