### ISSUE TITLE
Codable doesn't conform to ReadableWritable

### ISSUE THREAD

**Issue by tal** [nvzqz/FileKit#61]
I'm not sure if this is an oversight, but there's no default conformance for `Codable` to `ReadableWriteable`.

This conformance would allow for `File<DataType: ReadableWritable>` to work with any `Codable` and appears to be the intent as listed in the readme.

**Comment by phimage** [comment]
@tal If you have any idea of elegant implementation, you can propose it, or you can also PR

With the current implementation you can do that
```swift
typealias JSONReadableWritable = JSONWritable & JSONReadable // Just to be shorter if used many times

struct Test: JSONReadableWritable {
    var test: String
}
// then you can use File<Test> or make an alias
typealias TestFile = File<Test> // File need a concrete type, no protocol

```
The encoder and decoder used are static variable in `FileKit`

---

I will add in FileKit `JSONReadableWritable` and `PropertyListReadableWritable`
