### ISSUE TITLE
'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'

### ISSUE THREAD

**Issue by ArturGasparyan** [nvzqz/FileKit#66]
In **Image+FileKit.swift** on line 66 I get the following error:

`'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'`

Changing `self.pngData()` to `UIImagePNGRepresentation(self)` solves the issue. Please, kindly update.

**Comment by phimage** [comment]
https://developer.apple.com/documentation/uikit/uiimage/1624096-pngdata
You use an old swift version I think
