### ISSUE TITLE
No way to get file base name (filename without extension)?

### ISSUE THREAD

**Issue by JetForMe** [nvzqz/FileKit#69]
Is there no way to get file base name (filename without extension)?

**Comment by lechuckcaptain** [comment]
Something like that should do the trick?

```swift
extension Path {

    var fileOnlyName: String {
        guard pathExtension.count > 0 else {
            return fileName
        }

        let extLen = pathExtension.count + 1
        let nameOnlyLen = fileName.count - extLen
        return String(fileName.prefix(nameOnlyLen))
    }
}
```

**Comment by JetForMe** [comment]
Of course I can do that. What I was hoping for was for that to already be included in FileKit.

**Comment by lechuckcaptain** [comment]
Sure, just wanted to have a feedback before submitting a pull request 😄

**Comment by JetForMe** [comment]
Ah in that case, that seems as good as any other way of doing it.
