### ISSUE TITLE
save file from Alamofire

### ISSUE THREAD

**Issue by subinkk08** [nvzqz/FileKit#7]
I am  getting a file base64 string from alamofire . how to save  as a file

**Comment by phimage** [comment]
Did you use `Alamofire.download` or `Alamofire.request`?

**Comment by subinkk08** [comment]
HI sorry for the delay . i was busy with some other things.. Its worked fine ..thanks for the quick reply

**Comment by vinbhai4u** [comment]
@phimage its not working now 

I think FKPath is not what u have to use in latest version?

**Comment by phimage** [comment]
@vinbhai4u see release https://github.com/nvzqz/FileKit/releases
`FKPath` become `Path`

**Comment by vinbhai4u** [comment]
I tried Path.UserDocuments i cannot access it

**Comment by vinbhai4u** [comment]
@phimage can u update the above code for that it works for the latest version?

**Comment by phimage** [comment]
@vinbhai4u just remove FK, nothing more

**Comment by vinbhai4u** [comment]
I tried, Sorry I am very new to swift and iOS development :(

**Comment by phimage** [comment]
even if you are new you cannot ask people to do your job by providing the full code tested and ready to work

try code, then if you have error ask the meaning of the error
- if it is a FileKit error, you can ask here but ...
- if this is a general error, swift syntax etc..., stackoverflow or any forum

**Comment by vinbhai4u** [comment]
Sorry about that, but I figured it out

updating the code for future reference.

Alamofire.download(.GET, "download link") { temporaryURL, response in
            let suggestedFilename = response.suggestedFilename
            let url = NSURL(fileURLWithPath: Path.UserTemporary.description
                + suggestedFilename! as String)
            print(url)
            return url  // or FKPath(suggestedFilename) if not compil
        }

@phimage, thanks for your help.
