### ISSUE TITLE
Need way to append a path extension without removing anything after a period

### ISSUE THREAD

**Issue by JetForMe** [nvzqz/FileKit#70]
Setting `.pathExtension` replaces any possible path extension on the Path, even if it doesn't actually have one (e.g. a file named "Image 2019-09-18 19.43.38.067"). Path needs `append(extension: String)` or some such.

**Comment by phimage** [comment]
this replace
```swift
file.pathExtension = "myext"
```

---

to append to current extension ("" if no ext)
```swift
file.pathExtension = file.pathExtension+ "myext"
```

of make and extension
```swift
extension Path {
  mutating func appendToExtension(_ toAppend: String) {
        self.pathExtension = pathExtension + toAppend
    }
}
```
