### ISSUE TITLE
Please update cocoapods version to 6.0.0

### ISSUE THREAD

**Issue by luoxiu** [nvzqz/FileKit#73]
The latest version on cocoapods is 5.2.0, please update to 6.0.0, Thanks! 

![image](https://user-images.githubusercontent.com/18638838/87905912-2d2b3b80-ca94-11ea-8901-a6f184c04e43.png)

**Comment by luoxiu** [comment]
@phimage

**Comment by luoxiu** [comment]
@nvzqz

**Comment by nemowon** [comment]
@nvzqz

**Comment by nemowon** [comment]
@phimage

**Comment by phimage** [comment]
I have no access to cocopod account

in podfile you could use commit, branch, head code
And if you have some issue, clone to your github and point to a specific
git and branch
